name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - uses: actions/checkout@v2
    - name: Build
      working-directory: "Sources/"
      run: swift build -v
    - name: Run tests
      run: swift test -v
